### ISSUE TITLE
Difference between -s and -S

### ISSUE THREAD

**Issue by hyperknot** [topojson/topojson-simplify#12]
Since I have to use super tiny values for -s, like 1e-8 etc. I wanted to ask if I could use -S instead. What is the diffeference between them? Is there any downside in using `-s 1e-8`?

**Comment by mbostock** [comment]
Per the README, -s specifies the simplification threshold as an area value in steradians, whereas -S specifies it as a quantile. The appropriate value will depend on the use case.
